#!/bin/bash

function progress-bar {
    # Process data
    let _progress=(${1}*100/${2}*100)/100
    let _done=(${_progress}*4)/10
    let _left=40-$_done

    # Build progressbar string lengths
    _fill=$(printf "%${_done}s")
    _empty=$(printf "%${_left}s")

    # 1.2 Build progressbar strings and print the ProgressBar line
    # 1.2.1 Output example:
    # 1.2.1.1 Progress : [########################################] 100%
    printf "\rProgress : [${_fill// /#}${_empty// /-}] ${_progress}%% ${1}/${2}"

}

function expr1 {
    FILE=results/experiment3/experiment3-results.csv

    # run python script
}

function expr2 {
    let iterations=10

    for combo in 0 1 2 3
    do
        for (( cbr=0; cbr<10; cbr++ ))
        do
            for (( i=0; i < $iterations; i++ ))
            do
                ns experiment2.tcl $i $combo $cbr
            done
        done
    done

    # run python script
}

function expr3 {
    FILE=results/experiment3/experiment3-results.csv

    # run python script
}

# Should have command line args to run specific tests X times
expr2
