default:
	echo "Python doesn't need compiling"

clean:
	rm -rf __pycache__
	rm -f *.pyc

run:
	./webcrawler -v INFO 001111718 7R63P2NO
	./webcrawler -v INFO 001160850 CO5NFWNB

test:
	python3 -m unittest discover
