#!/bin/bash

# Usage: ./deployCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>

dns_server="cs5700cdnproject.ccs.neu.edu"
port=$2
origin=$4
domain=$6
username=$8
keyfile=${10}
http_servers[0]="ec2-52-0-73-113.compute-1.amazonaws.com"
http_servers[1]="ec2-52-16-219-28.eu-west-1.compute.amazonaws.com"
http_servers[2]="ec2-52-11-8-29.us-west-2.compute.amazonaws.com"
http_servers[3]="ec2-52-8-12-101.us-west-1.compute.amazonaws.com"
http_servers[4]="ec2-52-28-48-84.eu-central-1.compute.amazonaws.com"
http_servers[5]="ec2-52-68-12-77.ap-northeast-1.compute.amazonaws.com"
http_servers[6]="ec2-52-74-143-5.ap-southeast-1.compute.amazonaws.com"
http_servers[7]="ec2-52-64-63-125.ap-southeast-2.compute.amazonaws.com"
http_servers[8]="ec2-54-94-214-108.sa-east-1.compute.amazonaws.com"


echo "DNS: $dns_server"
echo "PORT: $port"
echo "ORIGIN: $origin"
echo "DOMAIN: $domain"
echo "USERNAME: $username"
echo "KEYFILE: $keyfile"
echo ""


# Make the dist folders
make dist

# Copy Files to DNS Server
ssh -i $keyfile $username@$dns_server "rm -rf dns_server; mkdir -p dns_server"
scp -r -i $keyfile dns_dist/* $username@$dns_server:dns_server
echo ""

# Copy Files to HTTP Server
for server in "${http_servers[@]}"
do
    echo "Uploading HTTP Server to $server."
    ssh -i $keyfile $username@$server "rm -rf http_server; mkdir -p http_server"
    scp -r -i $keyfile http_dist/* $username@$server:http_server
    echo ""
done

# Clean up dist folders
make clean_dist
